version: '2'
services:
  db:
    image: postgres:10.3-alpine

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    ports:
      - 6379:6379

  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/app'
    env_file:
      - .env

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/myapp
    ports:
      - "5000:3000"
    depends_on:
      - db
