# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d683808c35928296aad11d07f09107d8fdf22e5267f640e156ece23301922d058fa6e63cbf98979911bd12004d02e203a97745f7d90cef92d39e068b734e0a7

test:
  secret_key_base: e4129e4e2e264f9f29a5c5f2d0c56dacc1725b3db08af965159ffc3cff32180a7cd75b55958fa2762d6c1a45f31c4c5747efb293e656c081ea87e9323f1700b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
